l4ingress_app4_app4ns1:
- 10.133.136.92
- 10.133.136.93
l4ingress_app4_app4ns2:
- 10.133.136.94
- 10.133.136.95
- 10.133.136.96
- 10.133.136.97
- 10.133.136.98
- 10.133.136.99
- 10.133.136.100
l4ingress_app4_app4ns3:
- 10.133.136.101
- 10.133.136.102
- 10.133.136.103
- 10.133.136.104
- 10.133.136.105
l4ingress_app4_app4ns4:
- 10.133.136.106
- 10.133.136.107
- 10.133.136.108
