l4ingress_app1_app1ns1:
- 10.133.146.60
- 10.133.146.61
- 10.133.146.62
- 10.133.146.63
l4ingress_app1_app1ns2:
- 10.133.146.64
- 10.133.146.65
- 10.133.146.66
- 10.133.146.67
- 10.133.146.68
- 10.133.146.69
- 10.133.146.70
- 10.133.146.71
- 10.133.146.72
l4ingress_app2_app2ns1:
- 10.133.146.73
- 10.133.146.74
- 10.133.146.75
- 10.133.146.76
- 10.133.146.77
l4ingress_app3_app3ns1:
- 10.133.146.78
- 10.133.146.79
- 10.133.146.80
- 10.133.146.81
- 10.133.146.82
