l4ingress_app1_app1ns1:
- 10.133.136.60
- 10.133.136.61
- 10.133.136.62
- 10.133.136.63
- 10.133.136.64
- 10.133.136.65
- 10.133.136.66
l4ingress_app1_app1ns2:
- 10.133.136.67
- 10.133.136.68
- 10.133.136.69
- 10.133.136.70
- 10.133.136.71
- 10.133.136.72
- 10.133.136.73
l4ingress_app1_app1ns3:
- 10.133.136.74
- 10.133.136.75
- 10.133.136.76
- 10.133.136.77
- 10.133.136.78
- 10.133.136.79
- 10.133.136.80
l4ingress_app2_app2ns1:
- 10.133.136.81
- 10.133.136.82
- 10.133.136.83
- 10.133.136.84
- 10.133.136.85
- 10.133.136.86
l4ingress_app3_app3ns1:
- 10.133.136.87
- 10.133.136.88
- 10.133.136.89
- 10.133.136.90
- 10.133.136.91
l4ingress_app4_app4ns1:
- 10.133.136.92
- 10.133.136.93
l4ingress_app4_app4ns2:
- 10.133.136.94
- 10.133.136.95
- 10.133.136.96
- 10.133.136.97
- 10.133.136.98
- 10.133.136.99
- 10.133.136.100
l4ingress_app4_app4ns3:
- 10.133.136.101
- 10.133.136.102
- 10.133.136.103
- 10.133.136.104
- 10.133.136.105
l4ingress_app4_app4ns4:
- 10.133.136.106
- 10.133.136.107
- 10.133.136.108
