l4ingress_app1_app1ns1:
- 10.133.138.60
- 10.133.138.61
- 10.133.138.62
- 10.133.138.63
- 10.133.138.64
- 10.133.138.65
- 10.133.138.66
l4ingress_app1_app1ns3:
- 10.133.138.67
- 10.133.138.68
- 10.133.138.69
- 10.133.138.70
- 10.133.138.71
