l4ingress_app1_app1ns2:
- 10.133.147.60
- 10.133.147.61
l4ingress_app2_app2ns1:
- 10.133.147.62
- 10.133.147.63
- 10.133.147.64
- 10.133.147.65
- 10.133.147.66
- 10.133.147.67
- 10.133.147.68
- 10.133.147.69
- 10.133.147.70
- 10.133.147.71
l4ingress_app3_app3ns1:
- 10.133.147.72
- 10.133.147.73
- 10.133.147.74
- 10.133.147.75
- 10.133.147.76
- 10.133.147.77
- 10.133.147.78
- 10.133.147.79
- 10.133.147.80
