l4ingress_app1_app1ns1:
- 10.133.148.60
- 10.133.148.61
l4ingress_app1_app1ns2:
- 10.133.148.62
l4ingress_app1_app1ns3:
- 10.133.148.63
- 10.133.148.64
- 10.133.148.65
- 10.133.148.66
- 10.133.148.67
- 10.133.148.68
l4ingress_app2_app2ns1:
- 10.133.148.69
- 10.133.148.70
- 10.133.148.71
l4ingress_app3_app3ns1:
- 10.133.148.72
- 10.133.148.73
- 10.133.148.74
- 10.133.148.75
- 10.133.148.76
- 10.133.148.77
- 10.133.148.78
- 10.133.148.79
- 10.133.148.80
