l4ingress_app1_app1ns1:
- 10.133.137.60
l4ingress_app1_app1ns2:
- 10.133.137.61
- 10.133.137.62
- 10.133.137.63
- 10.133.137.64
- 10.133.137.65
- 10.133.137.66
- 10.133.137.67
- 10.133.137.68
- 10.133.137.69
- 10.133.137.70
l4ingress_app1_app1ns3:
- 10.133.137.71
- 10.133.137.72
- 10.133.137.73
l4ingress_app2_app2ns1:
- 10.133.137.74
- 10.133.137.75
- 10.133.137.76
- 10.133.137.77
- 10.133.137.78
- 10.133.137.79
- 10.133.137.80
- 10.133.137.81
- 10.133.137.82
l4ingress_app3_app3ns1:
- 10.133.137.83
- 10.133.137.84
- 10.133.137.85
- 10.133.137.86
- 10.133.137.87
l4ingress_app4_app4ns1:
- 10.133.137.88
- 10.133.137.89
l4ingress_app4_app4ns2:
- 10.133.137.90
- 10.133.137.91
l4ingress_app4_app4ns3:
- 10.133.137.92
- 10.133.137.93
- 10.133.137.94
- 10.133.137.95
- 10.133.137.96
- 10.133.137.97
l4ingress_app4_app4ns4:
- 10.133.137.98
- 10.133.137.99
- 10.133.137.100
- 10.133.137.101
- 10.133.137.102
