l4ingress_app1_app1ns1:
- 10.133.138.60
- 10.133.138.61
- 10.133.138.62
- 10.133.138.63
- 10.133.138.64
- 10.133.138.65
- 10.133.138.66
l4ingress_app1_app1ns3:
- 10.133.138.67
- 10.133.138.68
- 10.133.138.69
- 10.133.138.70
- 10.133.138.71
l4ingress_app2_app2ns1:
- 10.133.138.72
- 10.133.138.73
- 10.133.138.74
- 10.133.138.75
- 10.133.138.76
- 10.133.138.77
- 10.133.138.78
- 10.133.138.79
- 10.133.138.80
- 10.133.138.81
l4ingress_app3_app3ns1:
- 10.133.138.82
- 10.133.138.83
l4ingress_app4_app4ns3:
- 10.133.138.84
- 10.133.138.85
- 10.133.138.86
- 10.133.138.87
l4ingress_app4_app4ns4:
- 10.133.138.88
- 10.133.138.89
- 10.133.138.90
- 10.133.138.91
- 10.133.138.92
