l4ingress_app1_app1ns1:
- 10.133.136.60
- 10.133.136.61
- 10.133.136.62
- 10.133.136.63
- 10.133.136.64
- 10.133.136.65
- 10.133.136.66
l4ingress_app1_app1ns2:
- 10.133.136.67
- 10.133.136.68
- 10.133.136.69
- 10.133.136.70
- 10.133.136.71
- 10.133.136.72
- 10.133.136.73
l4ingress_app1_app1ns3:
- 10.133.136.74
- 10.133.136.75
- 10.133.136.76
- 10.133.136.77
- 10.133.136.78
- 10.133.136.79
- 10.133.136.80
